### ISSUE TITLE
Problems switching to s3 

### ISSUE THREAD

**Issue by jayallenmn** [paulcwarren/spring-content-gettingstarted#1]
Hey there,

I'm trying to switch to an s3 store by changing the dependency in the pom from spring-content-fs-boot-starter to spring-content-s3-boot-starter.  When I rebuild and run I get:

***************************
APPLICATION FAILED TO START
***************************

Description:

Field contentStore in gettingstarted.FileContentController required a bean of type 'gettingstarted.FileContentStore' that could not be found.

Looks like I need to rewrite the gettingstarted code to use s3 - am I missing something?

Jay

**Comment by paulcwarren** [comment]
Hi Jay,

You would have to change the dependency (as you suggest) and provide the necessary configuration beans for s3.  I have pushed the changes required on branch `gettingstarted-s3` for you to have a look at/pull.  You also have to provide your Amazon access and secret keys are environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` to the JVM.  

Let me know if this helps
_Paul

**Comment by jayallenmn** [comment]
Hey thanks Paul, this is great. Will give it a shot.  One question, is the s3 endpoint exposed as an environment variable?  We'd like to use an s3-compatible service with a different endpoint...

**Comment by paulcwarren** [comment]
Hi Jay,  I think you can, yes.  I just pushed [another change](https://github.com/paulcwarren/spring-content-gettingstarted/commit/1653b80cce68d45fedaa2a9f32f4140ecc2946ce) to the `gettingstarted-s3` branch.

Honestly, with the current release (0.0.3) we didn't do a great job making s3 generic so it can be used for other clients so whilst it seems possible to set the client endpoint it *must* be done after the underlying `S3ResourceTemplate` bean has been initialized (because it utilizes the `Region` bean which resets the endpoint back to an amazon URI).  This ordering can probably be done with clever autoconfigure trickery or, as I did, simply put after the spring boot app has been started.  This isn't ideal but it should work.

Fortunately, in the upcoming release (0.0.4) the s3 connection is handled a little differently and it is up to the application to contribute the `SimpleStorageResourceLoader` bean and therefore you'll have complete (and much cleaner) control over the connection.  Have a look at [this](https://github.com/paulcwarren/spring-content-examples/blob/master/spring-eg-content-s3/src/test/java/examples/S3Config.java#L51-L54) from the s3 example in the set of examples projects.

**Comment by jayallenmn** [comment]
hey Paul - been discussing this with @maximilien so tagging him here

**Comment by paulcwarren** [comment]
Thanks.  And actually I think we can close this issue as this was addressed in the 0.0.4 release.  Are you okay with that?

**Comment by maximilien** [comment]
Thanks for all the info. Thanks for the tip of v0.0.4 @paulcwarren

**Comment by jayallenmn** [comment]
Yep, thanks again Paul!
